AUTO_ADD_GLOBAL_DEFINE_BY_NAME = MTK_MAGICONFERENCE_SUPPORT MTK_HAC_SUPPORT CUSTOM_KERNEL_PDR_SENSOR MTK_EMBMS_SUPPORT MTK_SIM_LOCK_POWER_ON_WRITE_PROTECT MTK_CROSSMOUNT_MULTI_CH_SUPPORT MTK_MULTIPLE_TDLS_SUPPORT MTK_MODEM_MONITOR_SUPPORT MTK_BT_BLUEDROID_AVRCP_TG_16 MTK_CROSSMOUNT_SUPPORT CUSTOM_KERNEL_ANSWER_CALL_SENSOR MTK_CAM_STEREO_DENOISE_SUPPORT CUSTOM_KERNEL_UNCALI_MAG_SENSOR CUSTOM_KERNEL_UNCALI_GYRO_SENSOR MTK_BLULIGHT_DEFENDER_SUPPORT MTK_LCM_DEVICE_TREE_SUPPORT MTK_BT_BLUEDROID_A2DP_APTX MTK_NVCONFIG_PARTITION_SUPPORT MTK_BT_BLUEDROID_HFP_AG_17 MTK_AURISYS_PHONE_CALL_SUPPORT MTK_HEADSET_ACTIVE_NOISE_CANCELLATION MTK_DYNAMIC_SBP_SUPPORT MTK_FACTORY_GAMMA_SUPPORT MTK_VT3G324M_SUPPORT MTK_WFC_SUPPORT MTK_BT_BLUEDROID_AVRCP_TG_15 MTK_BT_BLUEDROID_PLUS MTK_CAM_VSDOF_SUPPORT MTK_ECCCI_C2K MTK_EXTERNAL_SIM_SUPPORT MTK_EFUSE_WRITER_SUPPORT MTK_FACTORY_MODE_IN_GB2312 MTK_A1_FEATURE MTK_AUDIO_TUNNELING_SUPPORT CUSTOM_KERNEL_HEART_RATE_SENSOR CUSTOM_KERNEL_SENSORHUB CUSTOM_KERNEL_TILT_DETECTOR_SENSOR CUSTOM_KERNEL_IN_POCKET_SENSOR CUSTOM_KERNEL_WAKE_GESTURE_SENSOR CUSTOM_KERNEL_FACE_DOWN_SENSOR CUSTOM_KERNEL_PICK_UP_SENSOR CUSTOM_KERNEL_GLANCE_GESTURE_SENSOR CUSTOM_KERNEL_PEDOMETER CUSTOM_KERNEL_SHAKE_SENSOR CUSTOM_KERNEL_PEDOMETERENSOR CUSTOM_KERNEL_ACTIVITY_SENSOR CUSTOM_KERNEL_SIGNIFICANT_MOTION_SENSOR CUSTOM_KERNEL_STEP_COUNTER MTK_GMO_ROM_OPTIMIZE MTK_GMO_RAM_OPTIMIZE MTK_ENABLE_MD3 SENSOR_BATCH_SUPPORT MTK_EPDG_SUPPORT MTK_LOSSLESS_BT_SUPPORT MTK_DTAG_DUAL_APN_SUPPORT MTK_DEINTERLACE_SUPPORT MTK_WIFI_MCC_SUPPORT MTK_JEITA_STANDARD_SUPPORT MTK_AUDIO_ALAC_SUPPORT MTK_BQ24261_SUPPORT MTK_REGIONALPHONE_SUPPORT MTK_VIDEO_VP8ENC_SUPPORT LENOVO_X2 MTK_BQ24250_SUPPORT X2_BQ27531_SUPPORT X2_CHARGING_STANDARD_SUPPORT MTK_MAX77819_SUPPORT MTK_PCA9575A_SUPPORT MTK_MD_LOW_BAT_SUPPORT MTK_ALPS_BOX_TVE_SUPPORT MTK_EXTMD_NATIVE_DOWNLOAD_SUPPORT MTK_ALPS_BOX_DONGLE_SUPPORT MTK_ETHERNET_SUPPORT MTK_BESSURROUND_SUPPORT MTK_BOX_AUDIO_DDPLUS_SUPPORT MTK_PLAYBACK_60FPS_TO_30FPS MTK_CAM_MMSDK_SUPPORT MTK_ANT_SUPPORT MTK_MIRAVISION_SETTING_SUPPORT MTK_PUMP_EXPRESS_SUPPORT MTK_BQ24157_SUPPORT MTK_MPEG_DASH_SUPPORT MTK_VOLTE_SUPPORT MTK_IMS_SUPPORT MTK_VOW_SUPPORT MTK_IPTV_SUPPORT MTK_PASSPOINT_R2_SUPPORT MTK_EXTERNAL_DONGLE_SUPPORT MTK_ALPS_BOX_SUPPORT MTK_OD_SUPPORT MTK_BQ24296_SUPPORT MTK_CAM_HDR_SUPPORT MTK_TC1_FEATURE MTK_BATTERY_PROTECT MTK_WIRELESS_CHARGER_SUPPORT MTK_CAM_STEREO_CAMERA_SUPPORT MTK_BESLOUDNESS_SUPPORT MTK_CAM_VHDR_SUPPORT MTK_CAM_EIS_SUPPORT MTK_CAM_VIDEO_FACEBEAUTY_SUPPORT MTK_CAM_FACEBEAUTY_SUPPORT MTK_WFD_SINK_UIBC_SUPPORT MTK_WFD_SINK_SUPPORT MTK_CAM_VSS_SUPPORT MTK_CAM_ZSD_SUPPORT MTK_POWER_EXT_DETECT MTK_CAM_LOMO_SUPPORT MTK_POST_PROCESS_FRAMEWORK_SUPPORT MTK_CAM_DEPTH_AF_SUPPORT MTK_MERGE_INTERFACE_SUPPORT MTK_CAM_NATIVE_PIP_SUPPORT MTK_CAM_NR3D_SUPPORT MTK_CAM_SINGLE_3DSHOT_SUPPORT MTK_CAM_AUTORAMA_SUPPORT MTK_CAM_IMAGE_REFOCUS_SUPPORT MTK_CAM_ASD_SUPPORT MTK_CAM_FD_SUPPORT MTK_MLC_NAND_SUPPORT MTK_FORCE_CLUSTER1 TRUSTONIC_TEE_SUPPORT MTK_RAWFS_NAND_SUPPORT MTK_LOMO_SUPPORT MTK_EXTERNAL_LDO MTK_PMIC_MT6397 MTK_TOUCH_BOOST MTK_SLOW_MOTION_VIDEO_SUPPORT MTK_VIDEO_HEVC_SUPPORT MTK_AUTO_DETECT_ALSPS MTK_GPT_SCHEME_SUPPORT MT6280_SUPER_DONGLE MTK_PRIVACY_PROTECTION_LOCK MTK_SIM_RECOVERY MTK_FAN5402_SUPPORT MTK_AUDIO_HD_REC_SUPPORT MTK_AUDIO MTK_CLEARMOTION_SUPPORT MTK_FSCK_TUNE MTK_NEW_COMBO_EMMC_SUPPORT MTK_PERSIST_PARTITION_SUPPORT MTK_DX_HDCP_SUPPORT MTK_COMBO_NAND_SUPPORT MTK_SMARTBOOK_SUPPORT MTK_DFO_RESOLUTION_SUPPORT MTK_HIGH_RESOLUTION_AUDIO_SUPPORT MTK_AUDIO_EXTCODEC_SUPPORT MTK_SUBTITLE_SUPPORT MTK_SDIOAUTOK_SUPPORT MTK_MSDC1_NOT_SUPPORT_SDR104 MTK_FEMTO_CELL_SUPPORT MTK_CHIPTEST_INT MTK_USER_ROOT_SWITCH MTK_ENABLE_MD5 MTK_WMV_PLAYBACK_SUPPORT MTK_WMA_PLAYBACK_SUPPORT MTK_MOBILE_MANAGEMENT MTK_PARTITION_TABLE_PLAIN_TEXT MTK_DOLBY_DAP_SUPPORT MTK_BQ24156_SUPPORT CUSTOM_KERNEL_BAROMETER MTK_BQ24158_SUPPORT MTK_TABLET_PLUGIN_BUILD MTK_MULTI_PARTITION_MOUNT_ONLY_SUPPORT MTK_BQ24297_SUPPORT MTK_3GDONGLE_SUPPORT MTK_PM_STATS_SUPPORT MTK_AUDIO_DDPLUS_SUPPORT MTK_SEC_WFD_VIDEO_PATH_SUPPORT MTK_BATLOWV_NO_PANEL_ON_EARLY MTK_SIM_HOT_SWAP_COMMON_SLOT MTK_TER_SERVICE MTK_OWNER_SDCARD_ONLY_SUPPORT MTK_DRM_PLAYREADY_SUPPORT MTK_SHOW_MSENSOR_TOAST_SUPPORT MTK_AUDIO_CHANGE_SUPPORT IS_VCORE_USE_6333VCORE IS_VRF18_USE_6333VRF18 IS_VM_USE_6333VM MTK_VIDEO_AUTO_FLASH_SUPPORT MTK_AIV_SUPPORT MTK_WFD_HDCP_TX_SUPPORT PURE_AP_USE_EXTERNAL_MODEM MTK_NO_NEED_USB_LED MTK_HDMI_HDCP_SUPPORT MTK_INTERNAL_HDMI_SUPPORT MTK_INTERNAL_MHL_SUPPORT MTK_DMNR_TUNING_AT_MD NAND_OTP_SUPPORT MTK_DVFS_DISABLE_LOW_VOLTAGE_SUPPORT MTK_VOIP_ENHANCEMENT_SUPPORT MTK_HANDSFREE_DMNR_SUPPORT MTK_SWCHR_SUPPORT MTK_MT6333_SUPPORT MTK_DRM_KEY_MNG_SUPPORT MTK_SEC_VIDEO_PATH_SUPPORT MTK_WVDRM_L1_SUPPORT MTK_IN_HOUSE_TEE_SUPPORT MTK_DISABLE_POWER_ON_OFF_VOLTAGE_LIMITATION MTK_CTA_SUPPORT MTK_DFO_SUPPORT MTK_BIP_SCWS MTK_MDM_FUMO MTK_MDM_LAWMO MTK_MDM_SCOMO MTK_UART_USB_SWITCH MTK_AUDIO_RAW_SUPPORT MTK_MD_SHUT_DOWN_NT MTK_CACHE_MERGE_SUPPORT MTK_IPV6_TETHER_PD_MODE MTK_YMAL_SCATTER_FILE_SUPPORT MTK_RADIOOFF_POWER_OFF_MD MTK_MT8193_HDCP_SUPPORT MTK_PLATFORM_OPTIMIZE MTK_HW_ENHANCE MTK_PQ_SUPPORT MTK_AUDIO_ADPCM_SUPPORT HAVE_ADPCMENCODE_FEATURE MTK_2IN1_SPK_SUPPORT MTK_BQ27541_SUPPORT MTK_WFD_SUPPORT MTK_IPV6_TETHER_NDP_MODE MTK_TETHERING_EEM_SUPPORT MTK_AAL_SUPPORT MTK_KERNEL_POWER_OFF_CHARGING MTK_FLIGHT_MODE_POWER_OFF_MD MTK_ENABLE_MD1 MTK_ENABLE_MD2 MTK_ACMT_DEBUG MTK_MMPROFILE_SUPPORT MTK_GPS_SUPPORT MTK_MULTIBRIDGE_SUPPORT MTK_CAMCORDER_PROFILE_MID_MP4 MTK_FM_SUPPORT MTK_TABLET_PLATFORM MTK_AUTO_DETECT_MAGNETOMETER MTK_NCP1851_SUPPORT MTK_NFC_SUPPORT MTK_MASS_STORAGE MTK_COMBO_QUICK_SLEEP_SUPPORT MTK_MT8193_SUPPORT HAVE_AACENCODE_FEATURE MTK_FM_50KHZ_SUPPORT MTK_COMBO_SUPPORT CUSTOM_KERNEL_GYROSCOPE MTK_SHARED_SDCARD MTK_EMMC_DISCARD MTK_DSPIRDBG MTK_MULTI_STORAGE_SUPPORT CUSTOM_KERNEL_ALSPS MTK_ENABLE_VIDEO_EDITOR CUSTOM_KERNEL_ACCELEROMETER MTK_DUAL_MIC_SUPPORT MTK_WAPI_SUPPORT MTK_FD_SUPPORT MTK_DISPLAY_HIGH_RESOLUTION MTK_BT_SUPPORT MTK_TABLET_DRAM MTK_FACEBEAUTY_SUPPORT MTK_FAN5405_SUPPORT MTK_BQ24160_SUPPORT MTK_HIGH_QUALITY_THUMBNAIL MTK_SPH_EHN_CTRL_SUPPORT MTK_FM_TX_SUPPORT MTK_BRAZIL_CUSTOMIZATION_VIVO MTK_BRAZIL_CUSTOMIZATION_CLARO MTK_IPV6_SUPPORT MTK_AUTORAMA_SUPPORT MTK_EAP_SIM_AKA MTK_BSP_PACKAGE MTK_BRAZIL_CUSTOMIZATION MTK_NVRAM_SECURITY CUSTOM_KERNEL_MAGNETOMETER MTK_WLANBT_SINGLEANT MTK_WLAN_SUPPORT MTK_TETHERINGIPV6_SUPPORT MTK_AUTO_DETECT_ACCELEROMETER HAVE_CMMB_FEATURE MTK_MT8193_HDMI_SUPPORT MTK_EMMC_SUPPORT_OTP MTK_TB_APP_CALL_FORCE_SPEAKER_ON MTK_PRODUCT_INFO_SUPPORT MTK_FM_SHORT_ANTENNA_SUPPORT MTK_HDMI_SUPPORT MTK_M4U_SUPPORT MTK_MT8193_NFI_SUPPORT MTK_ION_SUPPORT MTK_FSCK_MSDOS_MTK MTK_BQ24196_SUPPORT MTK_FM_RX_SUPPORT MTK_WB_SPEECH_SUPPORT ENCRY_PARTITION_SUPPORT MTK_SD_REINIT_SUPPORT MTK_SENSOR_SUPPORT MTK_EMMC_SUPPORT MTK_COMBO_CORE_DUMP_SUPPORT MTK_DHCPV6C_WIFI MTK_EMULATOR_SUPPORT MTK_NAND_UBIFS_SUPPORT MTK_YAML_SCATTER_FILE_SUPPORT MTK_VIDEO_VP9_SUPPORT MTK_THERMAL_PA_VIA_ATCMD MTK_FLV_PLAYBACK_SUPPORT MTK_AUDIO_APE_SUPPORT MTK_AVI_PLAYBACK_SUPPORT USE_FRAUNHOFER_AAC MTK_DRM_APP MTK_OGM_PLAYBACK_SUPPORT MTK_MTKPS_PLAYBACK_SUPPORT MTK_MT6306_SUPPORT
AUTO_ADD_GLOBAL_DEFINE_BY_NAME_VALUE = MTK_FUSED_LOCATION_SUPPORT MTK_NFC_PACKAGE MTK_CAM_STEREO_CAMERA_FACING MTK_JPEG_HW_RESIZER_TYPE MAXIM_SPEAKER_SUPPORT MTK_VZW_CHIPTEST_MODE_SUPPORT MTK_CAM_ZSDHDR_SUPPORT MTK_CAM_ZSDMFB_SUPPORT MTK_AUDIO_MIC_INVERSE SIM_ME_LOCK_MODE CUSTOM_CONFIG_MAX_DRAM_SIZE MTK_MD_SBP_CUSTOM_VALUE MTK_CAM_MFB_SUPPORT MTK_CAM_CONTINUOUS_SHOT_MODE MTK_VIDEO_4KH264_SUPPORT MTK_HOTKNOT_SUPPORT MTK_TELEPHONY_BOOTUP_MODE_SLOT2 MTK_TELEPHONY_BOOTUP_MODE_SLOT1 MTK_NFC_SE_NUM MTK_OVERLAY_ENGINE_SUPPORT MTK_SIM1_SOCKET_TYPE MTK_SIM2_SOCKET_TYPE CUSTOM_KERNEL_MAIN2_IMGSENSOR CUSTOM_KERNEL_SSW MTK_LCM_PHYSICAL_ROTATION LCM_WIDTH MTK_SINGLE_3DSHOT_SUPPORT MTK_EXTERNAL_MODEM_SLOT MTK_NEON_SUPPORT LCM_HEIGHT MTK_NTFS_OPENSOURCE_SUPPORT
AUTO_ADD_GLOBAL_DEFINE_BY_VALUE = CUSTOM_HAL_LENS BOOT_LOGO MTK_AUDIO_BLOUD_CUSTOMPARAMETER_REV MTK_PLATFORM CUSTOM_KERNEL_LENS CUSTOM_KERNEL_MAIN_BACKUP_LENS MTK_MODEM_SUPPORT CUSTOM_KERNEL_MAIN_IMGSENSOR MTK_BT_CHIP MTK_WLAN_CHIP CUSTOM_KERNEL_SUB_BACKUP_IMGSENSOR CUSTOM_KERNEL_MAIN_BACKUP_IMGSENSOR CUSTOM_KERNEL_FLASHLIGHT CUSTOM_KERNEL_SUB_IMGSENSOR CUSTOM_KERNEL_SUB_LENS CUSTOM_KERNEL_IMGSENSOR MTK_FM_RX_AUDIO MTK_COMBO_CHIP MTK_GPS_CHIP CUSTOM_KERNEL_SUB_BACKUP_LENS CUSTOM_KERNEL_MAIN_LENS MTK_FM_TX_AUDIO MTK_FM_CHIP CUSTOM_KERNEL_MAIN2_IMGSENSOR BOOT_LOGO MTK_IRTX_PWM_SUPPORT
BOOT_LOGO = cu_lte_qvga
BUILD_KERNEL = yes
BUILD_LK = yes
BUILD_MD32 = no
BUILD_MTK_SDK =
BUILD_PRELOADER = yes
BUILD_UBOOT = no
CUSTOM_BUILD_VERNO =8121TO_P1
CUSTOM_CONFIG_MAX_DRAM_SIZE = 0x40000000
CUSTOM_HAL_ANT = mt6739_ant_m1
CUSTOM_HAL_AUDIOFLINGER = audio
CUSTOM_HAL_BLUETOOTH = bluetooth
CUSTOM_HAL_CAMERA = camera
CUSTOM_HAL_CAM_CAL = BRCB032GWZ_3 GT24c32a cat24c16
CUSTOM_HAL_COMBO = mt6739
CUSTOM_HAL_EEPROM = dummy_eeprom
CUSTOM_HAL_FLASHLIGHT = constant_flashlight
CUSTOM_HAL_IMGSENSOR = gc5025_mipi_raw gc2385_mipi_raw
CUSTOM_HAL_LENS = dummy_lens
CUSTOM_HAL_MAIN2_IMGSENSOR =
CUSTOM_HAL_MAIN_BACKUP_IMGSENSOR =
CUSTOM_HAL_MAIN_BACKUP_LENS = dummy_lens
CUSTOM_HAL_MAIN_IMGSENSOR =gc5025_mipi_raw
CUSTOM_HAL_MAIN_LENS = dummy_lens
CUSTOM_HAL_MSENSORLIB =akl
CUSTOM_HAL_SENSORS = sensor
CUSTOM_HAL_SUB_BACKUP_IMGSENSOR =
CUSTOM_HAL_SUB_BACKUP_LENS = 
CUSTOM_HAL_SUB_IMGSENSOR = gc2385_mipi_raw
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_HIFI_SENSORS = no
CUSTOM_KERNEL_ACCELEROMETER = yes
CUSTOM_KERNEL_ACTIVITY_SENSOR = no
CUSTOM_KERNEL_ALSPS = yes
CUSTOM_KERNEL_ANSWER_CALL_SENSOR =
CUSTOM_KERNEL_BAROMETER = no
CUSTOM_KERNEL_BATTERY = battery
CUSTOM_KERNEL_BIOMETRIC_SENSOR = no
CUSTOM_KERNEL_CAMERA = camera
CUSTOM_KERNEL_CAM_CAL = BRCB032GWZ_3 GT24c32a cat24c16
CUSTOM_KERNEL_CORE = src
CUSTOM_KERNEL_DCT = dct
CUSTOM_KERNEL_DEVICE_ORIENTATION =
CUSTOM_KERNEL_EEPROM = dummy_eeprom
CUSTOM_KERNEL_FACE_DOWN_SENSOR = no
CUSTOM_KERNEL_FLASHLIGHT = constant_flashlight
CUSTOM_KERNEL_GLANCE_GESTURE_SENSOR = no
CUSTOM_KERNEL_GYROSCOPE = no
CUSTOM_KERNEL_HEADSET = accdet
CUSTOM_KERNEL_IMGSENSOR = gc5025_mipi_raw gc2385_mipi_raw
CUSTOM_KERNEL_IN_POCKET_SENSOR = no
CUSTOM_KERNEL_KPD = kpd
CUSTOM_KERNEL_LEDS = mt65xx
CUSTOM_KERNEL_LENS = dummy_lens
CUSTOM_KERNEL_MAGNETOMETER = no
CUSTOM_KERNEL_MAIN2_BACKUP_IMGSENSOR =
CUSTOM_KERNEL_MAIN2_IMGSENSOR =
CUSTOM_KERNEL_MAIN_BACKUP_IMGSENSOR =
CUSTOM_KERNEL_MAIN_BACKUP_LENS = dummy_lens
CUSTOM_KERNEL_MAIN_IMGSENSOR =gc5025_mipi_raw
CUSTOM_KERNEL_MAIN_LENS = dummy_lens
CUSTOM_KERNEL_SUB_BACKUP_IMGSENSOR = 
CUSTOM_KERNEL_SUB_BACKUP_LENS = 
CUSTOM_KERNEL_SUB_IMGSENSOR =gc2385_mipi_raw
CUSTOM_KERNEL_SUB_LENS = dummy_lens

CUSTOM_KERNEL_MOTION_DETECT =
CUSTOM_KERNEL_ORIENTATION_SENSOR = no
CUSTOM_KERNEL_PDR_SENSOR = no
CUSTOM_KERNEL_PEDOMETER = no
CUSTOM_KERNEL_PICK_UP_SENSOR = no
CUSTOM_KERNEL_RTC = rtc
CUSTOM_KERNEL_SENSORHUB = no
CUSTOM_KERNEL_SHAKE_SENSOR = no
CUSTOM_KERNEL_SIGNIFICANT_MOTION_SENSOR = no
CUSTOM_KERNEL_SOUND = amp_6323pmic_spk
CUSTOM_KERNEL_SSW =
CUSTOM_KERNEL_STATIONARY_SENSOR =
CUSTOM_KERNEL_STEP_COUNTER =

CUSTOM_KERNEL_TILT_DETECTOR_SENSOR = no
CUSTOM_KERNEL_TOUCHPANEL = GT1XX
CUSTOM_KERNEL_UNCALI_GYRO_SENSOR =
CUSTOM_KERNEL_UNCALI_MAG_SENSOR =
CUSTOM_KERNEL_USB = mt6577
CUSTOM_KERNEL_VIBRATOR = vibrator
CUSTOM_KERNEL_WAKE_GESTURE_SENSOR = no
CUSTOM_MODEM = Modem_8121TO_P1_2G_B2B3B8_W_B1B8_TDS_A_F_4G_B1B3B5B8B34B39B40B41_BC0_V34
CUSTOM_SEC_AUTH_SUPPORT = no
CUSTOM_SEC_SIGNTOOL_SUPPORT = no
DCORE_TEST_MODE1 = no
DISABLE_EARPIECE = no
ENCRY_PARTITION_SUPPORT = no
EVB = no
EVDO_IR_SUPPORT = no
FEATURE_FTM_AUDIO_AUTOTEST = yes
FEATURE_FTM_AUDIO_TEST = yes
FPGA_EARLY_PORTING = no
GOOGLE_RELEASE_RIL = no
HAVE_AACENCODE_FEATURE = yes
HAVE_ADPCMENCODE_FEATURE = no
HAVE_APPC_FEATURE = no
HAVE_SRSAUDIOEFFECT_FEATURE = no
HAVE_VORBISENC_FEATURE = yes
IS_VCORE_USE_6333VCORE = no
IS_VM_USE_6333VM = no
IS_VRF18_USE_6333VRF18 = no
LCM_FAKE_HEIGHT = 0
LCM_FAKE_WIDTH = 0
LCM_HEIGHT = 320
LCM_WIDTH = 240
LIGHT_NVRAM_DAEMON = no
LINUX_KERNEL_VERSION = kernel-4.4
LOVELYFONTS_ICON_SHOW = no
LOVELYFONTS_SUPPORT = no
MAXIM_SPEAKER_SUPPORT = no
MCUPM_FW_USE_PARTITION = yes
MD32_TOOLCHAIN_MODULE = IPDesigner/12R2.36-64
MD5_SIZE = 0x01600000
MD5_SMEM_SIZE = 0x00200000
MICROTRUST_TEE_SUPPORT = no
MNTL_SUPPORT = no
MT6280_SUPER_DONGLE = no
MTK_2IN1_SPK_SUPPORT = no
MTK_3GDONGLE_SUPPORT = no
MTK_AAL_SUPPORT = yes
MTK_ACAO_SUPPORT = yes
MTK_ACDK_BUILD_DUMMY_ENG = no
MTK_ACMT_DEBUG = no
MTK_AEE_SUPPORT = yes
MTK_AFPSGO_FBT_GAME = yes
MTK_AGPS_APP = yes
MTK_AIV_SUPPORT = no
MTK_ALARM_AWARE_UPLINK_SUPPORT = yes
MTK_ALPS_BOX_DONGLE_SUPPORT = no
MTK_ALPS_BOX_SUPPORT = no
MTK_ALPS_BOX_TVE_SUPPORT = no
MTK_ALPS_GATEWAY_AP_ROUTER_SUPPORT = no
MTK_ALPS_GATEWAY_SUPPORT = no
MTK_ANDROID_FOR_WORK_SUPPORT = no
MTK_ANDROID_LOG_MUCH_COUNT = 4000
MTK_ANT_SUPPORT = no
MTK_AOD_SUPPORT = no
MTK_API_CHECK = yes
MTK_APKINSTALLER_APP = no
MTK_APPENDED_DTB_SUPPORT = yes
MTK_APP_GUIDE = yes
MTK_AP_SPEECH_ENHANCEMENT = no
MTK_ASR_SUPPORT = no
MTK_ATF_SUPPORT = yes
MTK_AUDENH_SUPPORT = no
MTK_AUDIO = yes
MTK_AUDIO_ADPCM_SUPPORT = yes
MTK_AUDIO_ALAC_SUPPORT = yes
MTK_AUDIO_APE_SUPPORT = yes
MTK_AUDIO_BLOUD_CUSTOMPARAMETER_REV = MTK_AUDIO_BLOUD_CUSTOMPARAMETER_V5
MTK_AUDIO_CHANGE_SUPPORT = no
MTK_AUDIO_CODEC_SUPPORT_TABLET = no
MTK_AUDIO_DDPLUS_SUPPORT = no
MTK_AUDIO_EXTCODEC_SUPPORT = no
MTK_AUDIO_GAIN_TABLE_SUPPORT = no
MTK_AUDIO_HD_REC_SUPPORT = yes
MTK_AUDIO_HYBRID_NLE_SUPPORT = no
MTK_AUDIO_MIC_INVERSE = no
MTK_AUDIO_NUMBER_OF_MIC = 2
MTK_AUDIO_NUMBER_OF_SPEAKER = 1
MTK_AUDIO_RAW_SUPPORT = yes
MTK_AUDIO_SPEAKER_PATH = int_lo_buf
MTK_AUDIO_TUNING_TOOL_VERSION = V2.2
MTK_AUDIO_TUNNELING_SUPPORT = no
MTK_AUIDO_MIC_INVERSE = no
MTK_AURISYS_FRAMEWORK_SUPPORT = yes
MTK_AURISYS_PHONE_CALL_SUPPORT = no
MTK_AUTOIP_SUPPORT = no
MTK_AUTORAMA_SUPPORT = yes
MTK_AUTO_DETECT_ACCELEROMETER = no
MTK_AUTO_DETECT_ALSPS = no
MTK_AUTO_DETECT_MAGNETOMETER = no
MTK_AUTO_SANITY = no
MTK_AVI_PLAYBACK_SUPPORT = yes
MTK_AWS_SUPPORT = no
MTK_BASIC_PACKAGE = no
MTK_BATLOWV_NO_PANEL_ON_EARLY = no
MTK_BATTERY_PROTECT = no
MTK_BESLOUDNESS_RUN_WITH_HAL = no
MTK_BESLOUDNESS_SUPPORT = yes
MTK_BESSURROUND_SUPPORT = no
MTK_BG_POWER_SAVING_SUPPORT = yes
MTK_BG_POWER_SAVING_UI_SUPPORT = yes
MTK_BIP_SCWS = yes
MTK_BLULIGHT_DEFENDER_SUPPORT = no
MTK_BOX_AUDIO_DDPLUS_SUPPORT = no
MTK_BOX_CAM_SUPPORT = no
MTK_BQ24156_SUPPORT = no
MTK_BQ24157_SUPPORT = no
MTK_BQ24158_SUPPORT = no
MTK_BQ24160_SUPPORT = no
MTK_BQ24261_SUPPORT = no
MTK_BQ24296_SUPPORT = no
MTK_BQ24297_SUPPORT = no
MTK_BQ27541_SUPPORT = no
MTK_BRANCH = alps-mp-o1.mp1
MTK_BRAZIL_CUSTOMIZATION = no
MTK_BRAZIL_CUSTOMIZATION_CLARO = no
MTK_BRAZIL_CUSTOMIZATION_TIM = no
MTK_BRAZIL_CUSTOMIZATION_VIVO = no
MTK_BSP_PACKAGE = yes
MTK_BTLOGGER_SUPPORT = yes
MTK_BT_AVRCP_TG_MULTI_PLAYER_SUPPORT = no
MTK_BT_BLUEDROID_A2DP_APTX = no
MTK_BT_BLUEDROID_AVRCP_TG_15 = no
MTK_BT_BLUEDROID_AVRCP_TG_16 = no
MTK_BT_BLUEDROID_DUN_GW_12 = no
MTK_BT_BLUEDROID_HFP_AG_17 = no
MTK_BT_BLUEDROID_PLUS = yes
MTK_BT_CHIP = MTK_CONSYS_MT6739
MTK_BT_CUSTOM = no
MTK_BT_HOST_SNOOP_LOG_SUPPORT = yes
MTK_BT_INTEROP_EXTENSION = yes
MTK_BT_SUPPORT = yes
MTK_BT_WIFI_COEX_RADIO_MODIFY = no
MTK_BUFFER_COMPRESSION_SUPPORT = no
MTK_BUILD_VERNO = alps-mp-o1.mp1
MTK_BWC_SUPPORT = yes
MTK_C2K_LTE_MODE = 2
MTK_CACHE_MERGE_SUPPORT = no
MTK_CALENDAR_IMPORTER_APP = no
MTK_CAMCORDER_PROFILE_MID_MP4 = no
MTK_CAMERA_APP = no
MTK_CAM_ASD_SUPPORT = yes
MTK_CAM_AUTORAMA_SUPPORT = yes
MTK_CAM_CONTINUOUS_SHOT_MODE = 0
MTK_CAM_DEPTH_AF_SUPPORT = no
MTK_CAM_DUALPD_SUPPORT = yes
MTK_CAM_DUAL_ZOOM_MTK_FOV_SUPPORT = no
MTK_CAM_DUAL_ZOOM_SUPPORT = no
MTK_CAM_EIS_SUPPORT = yes
MTK_CAM_FACEBEAUTY_SUPPORT = no
MTK_CAM_FD_SUPPORT = no
MTK_CAM_HDR_DETECTION_MODE = 0
MTK_CAM_HDR_SUPPORT = no
MTK_CAM_IMAGE_REFOCUS_SUPPORT = NONE
MTK_CAM_LOMO_SUPPORT = yes
MTK_CAM_MFB_BUILDIN_SUPPORT = 0
MTK_CAM_MFB_SUPPORT = 0
MTK_CAM_MMSDK_SUPPORT = no
MTK_CAM_NATIVE_PIP_SUPPORT = no
MTK_CAM_NR3D_SUPPORT = no
MTK_CAM_PDO_TEST_ENABLE = no
MTK_CAM_SINGLE_3DSHOT_SUPPORT = no
MTK_CAM_STEREO_CAMERA_FACING = rear
MTK_CAM_STEREO_CAMERA_SUPPORT = no
MTK_CAM_STEREO_DENOISE_SUPPORT = no
MTK_CAM_SW_VERSION = ver1
MTK_CAM_USER_DBG_LOG_OFF = no
MTK_CAM_VHDR_SUPPORT = no
MTK_CAM_VIDEO_FACEBEAUTY_SUPPORT = no
MTK_CAM_VSDOF_SUPPORT = no
MTK_CAM_VSS_SUPPORT = yes
MTK_CAM_ZSDHDR_SUPPORT = no
MTK_CAM_ZSDMFB_SUPPORT = no
MTK_CAM_ZSD_SUPPORT = no
MTK_CARRIEREXPRESS_APK_INSTALL_SUPPORT = no
MTK_CARRIEREXPRESS_SWITCH_MODE = 1
MTK_CC33_SUPPORT = no
MTK_CDS_EM_SUPPORT = yes
MTK_CHAMELEON_DISPLAY_SUPPORT = no
MTK_CHARM_SUPPORT = no
MTK_CHIPTEST_INT = no
MTK_CHIP_VER = S01
MTK_CHIP_VERSION = 0
MTK_CIP_SUPPORT = no
MTK_CLEARMOTION_SUPPORT = no
MTK_CMAS_SUPPORT = no
MTK_CMCC_FT_PRECHECK_SUPPORT = no
MTK_CMCC_RCS_QRCODE_SUPPORT = no
MTK_COMBO_CHIP = CONSYS_6739
MTK_COMBO_NAND_SUPPORT = no
MTK_COMBO_SUPPORT = yes
MTK_CONSUMER_PARTIAL_UPDATE_SUPPORT = no
MTK_CPU = arm_cortexa7
MTK_CROSSMOUNT_MULTI_CH_SUPPORT = no
MTK_CROSSMOUNT_SUPPORT = no
MTK_CTA_SET = no
MTK_CTA_SUPPORT = no
MTK_CTM_SUPPORT = no
MTK_CTSC_MTBF_INTERNAL_SUPPORT = no
MTK_CT_VOLTE_SUPPORT = yes
MTK_CUSTOMERSERVICE_APP = no
MTK_CUSTOM_USERLOAD_ENGINEERMODE = yes
MTK_DEFAULT_DATA_OFF = no
MTK_DEFAULT_WRITE_DISK = no
MTK_DEINTERLACE_SUPPORT = yes
MTK_DEVREG_APP = no
MTK_CT4GREG_APP = no
MTK_DFO_RESOLUTION_SUPPORT = no
MTK_DHCPV6C_WIFI = yes
MTK_DIALER_SEARCH_SUPPORT = yes
MTK_DIGITAL_MIC_SUPPORT = no
MTK_DIGITS_SUPPORT = no
MTK_DISABLE_CAPABILITY_SWITCH = no
MTK_DISABLE_EFUSE = no
MTK_DISABLE_PERSIST_VSIM = no
MTK_DISABLE_POWER_ON_OFF_VOLTAGE_LIMITATION = no
MTK_DISPLAY_HIGH_RESOLUTION = no
MTK_DITHERING_SUPPORT = yes
MTK_DMNR_TUNING_AT_MD = no
MTK_DM_APP = no
MTK_DM_ENTRY_DISPLAY = no
MTK_DM_VERITY_OFF = yes
MTK_DOCOMO_SUPPORT = no
MTK_DOLBY_DAP_SUPPORT = no
MTK_DP_FRAMEWORK = yes
MTK_DRE30_SUPPORT = no
MTK_DRM_APP = yes
MTK_DRM_KEY_MNG_SUPPORT = no
MTK_DRM_PLAYREADY_SUPPORT = no
MTK_DSPIRDBG = no
MTK_DTAG_DUAL_APN_SUPPORT = no
MTK_DTBO_FEATURE = yes
MTK_DUAL_CHARGER_SUPPORT = no
MTK_DUAL_MIC_SUPPORT = no
MTK_DVFS_DISABLE_LOW_VOLTAGE_SUPPORT = no
MTK_DX_HDCP_SUPPORT = no
MTK_DYNAMIC_FPS_SUPPORT = no
MTK_DYNAMIC_SBP_SUPPORT = yes
MTK_EAP_SIM_AKA = yes
MTK_ECCCI_C2K = yes
MTK_EFUSE_WRITER_SUPPORT = no
MTK_EMBMS_SUPPORT = no
MTK_EMCAMERA_APP = yes
MTK_EMMC_DISCARD = no
MTK_EMMC_SUPPORT = yes
MTK_EMMC_SUPPORT_OTP = no
MTK_EMULATOR_SUPPORT = no
MTK_ENABLE_DIVX_DECODER = yes
MTK_ENABLE_MD1 = yes
MTK_ENABLE_MD2 = no
MTK_ENABLE_MD3 = no
MTK_ENABLE_MD5 = no
MTK_ENABLE_NATIVE_ASAN = no
MTK_ENABLE_S263_DECODER = no
MTK_ENABLE_VIDEO_EDITOR = no
MTK_ENCRYPTION_DEFAULT_OFF = no
MTK_ENCRYPTION_FDE_TO_FBE = no
MTK_ENCRYPTION_TYPE_FILE = no
MTK_ENGINEERMODE_APP = yes
MTK_EPDG_SUPPORT = yes
MTK_ESN_TRACK_APP = no
MTK_ETHERNET_SUPPORT = no
MTK_ETWS_SUPPORT = no
MTK_EXTERNAL_DONGLE_SUPPORT = no
MTK_EXTERNAL_LDO = no
MTK_EXTERNAL_MODEM_SLOT = 0
MTK_EXTERNAL_SIM_ONLY_SLOTS = 0
MTK_EXTERNAL_SIM_SUPPORT = no
MTK_EXTMD_NATIVE_DOWNLOAD_SUPPORT = no
MTK_FACEBEAUTY_SUPPORT = yes
MTK_FACTORY_GAMMA_SUPPORT = no
MTK_FACTORY_MODE_IN_GB2312 = yes
MTK_FACTORY_RESET_PROTECTION_SUPPORT = yes
MTK_FAN5402_SUPPORT = no
MTK_FAN5405_SUPPORT = no
MTK_FASTBOOT_SUPPORT = yes
MTK_FD_FORCE_REL_SUPPORT = no
MTK_FD_SUPPORT = yes
MTK_FEMTO_CELL_SUPPORT = no
MTK_FENCE_SUPPORT = yes
MTK_FILEMANAGER_APP = yes
MTK_FIRST_MD = 1
MTK_FLIGHT_MODE_POWER_OFF_MD = no
MTK_FLIGHT_MODE_POWER_OFF_MD_POLICY = 0
MTK_FLV_PLAYBACK_SUPPORT = yes
MTK_FMRADIO_APP = yes
MTK_FM_50KHZ_SUPPORT = no
MTK_FM_CHIP = MT6625_FM
MTK_FM_RX_AUDIO = FM_DIGITAL_INPUT
MTK_FM_RX_SUPPORT = yes
MTK_FM_SHORT_ANTENNA_SUPPORT = yes
MTK_FM_SUPPORT = yes
MTK_FM_TX_AUDIO = FM_DIGITAL_OUTPUT
MTK_FM_TX_SUPPORT = no
MTK_FORCE_CLUSTER1 = no
MTK_FOTA_ENTRY = no
MTK_FOTA_SUPPORT = no
MTK_FSCK_MSDOS_MTK = no
MTK_FSCK_TUNE = no
MTK_FUSED_LOCATION_SUPPORT = no
MTK_FW_UPGRADE = no
MTK_GAS_SERVICE_SUPPORT = yes
MTK_GAUGE_VERSION = 30
MTK_GLOBAL_PQ_SUPPORT = no
MTK_GMO_RAM_OPTIMIZE = yes
MTK_GMO_ROM_OPTIMIZE = yes
MTK_GOOGLEOTA_SUPPORT = no
MTK_GOOGLE_TRUSTY_SUPPORT = no
MTK_GPS_CHIP = MTK_GPS_MT6631
MTK_GPS_SUPPORT = yes
MTK_GPT_SCHEME_SUPPORT = yes
MTK_GPU_SUPPORT = yes
MTK_GPU_VERSION = rgx auckland 1.8ED
MTK_HAC_SUPPORT = no
MTK_HANDSFREE_DMNR_SUPPORT = yes
MTK_HDMI_HDCP_SUPPORT = no
MTK_HDMI_SUPPORT = no
MTK_HDR_VIDEO_SUPPORT = no
MTK_HEADER_SUPPORT = no
MTK_HEADSET_ACTIVE_NOISE_CANCELLATION = no
MTK_HIDL_PROCESS_CONSOLIDATION_ENABLED = yes
MTK_HIGH_QUALITY_THUMBNAIL = yes
MTK_HIGH_RESOLUTION_AUDIO_SUPPORT = no
MTK_HOTKNOT_SUPPORT = no
MTK_HW_ENHANCE = no
MTK_ICCS_SUPPORT = no
MTK_IMS_SUPPORT = yes
MTK_INCALL_HANDSFREE_DMNR = no
MTK_INCALL_NORMAL_DMNR = no
MTK_INCLUDE_MODEM_DB_IN_IMAGE = yes
MTK_INTERNAL_API_CHECK = no
MTK_INTERNAL_HDMI_SUPPORT = no
MTK_INTERNAL_LANG_SET = no
MTK_INTERNAL_MHL_SUPPORT = no
MTK_INT_MD_SPE_FOR_EXT_MD = no
MTK_IN_HOUSE_TEE_SUPPORT = no
MTK_ION_SUPPORT = yes
MTK_IPO_SUPPORT = no
MTK_IPTV_SUPPORT = no
MTK_IPV6_SUPPORT = yes
MTK_IPV6_TETHER_NDP_MODE = no
MTK_IPV6_TETHER_PD_MODE = no
MTK_IRAT_SUPPORT = yes
MTK_IRTX_PWM_SUPPORT = yes
MTK_IRTX_SUPPORT = no
MTK_JEITA_STANDARD_SUPPORT = no
MTK_JPEG_HW_RESIZER_TYPE = HW_RESIZER_TYPE_2
MTK_K64_SUPPORT=no
MTK_KERNEL_POWER_OFF_CHARGING = yes
MTK_LAUNCHER_UNREAD_SUPPORT = yes
MTK_LCM_DEVICE_TREE_SUPPORT = no
MTK_LCM_PHYSICAL_ROTATION = 0
MTK_LIVEWALLPAPER_APP = no
MTK_LOG2SERVER_APP = no
MTK_LOG2SERVER_INTERNAL = no
MTK_LOG_CUSTOMER_SUPPORT = yes
MTK_LOG_SUPPORT_GPS = yes
MTK_LOG_SUPPORT_MOBILE_LOG = yes
MTK_LOMO_SUPPORT = no
MTK_LWA_SUPPORT = no
MTK_M4U_SUPPORT = no
MTK_MAGICONFERENCE_SUPPORT = no
MTK_MASS_STORAGE = no
MTK_MD1_SUPPORT = 12
MTK_MD2_SUPPORT = 4
MTK_MD3_SUPPORT = 2
MTK_MD5_SUPPORT = 5
MTK_MDLOGGER_SUPPORT = yes
MTK_MDM_APP = no
MTK_MDM_FUMO = no
MTK_MDM_LAWMO = no
MTK_MDM_SCOMO = no
MTK_MD_DIRECT_TETHERING_SUPPORT = no
MTK_MD_LOW_BAT_SUPPORT = no
MTK_MD_SBP_CUSTOM_VALUE =
MTK_MD_SHUT_DOWN_NT = yes
MTK_MEMORY_COMPRESSION_SUPPORT = no
MTK_MERGE_INTERFACE_SUPPORT = no
MTK_META_RSSITRIGGER_SUPPORT = no
MTK_MIRAVISION_SETTING_SUPPORT = no
MTK_MKV_PLAYBACK_ENHANCEMENT = no
MTK_MLC_NAND_SUPPORT = no
MTK_MMPROFILE_SUPPORT = yes
MTK_MMUMAP_SUPPORT = no
MTK_MOBILE_MANAGEMENT = yes
MTK_MODEM_MONITOR_SUPPORT = yes
MTK_MODEM_SUPPORT =
MTK_MP2_PLAYBACK_SUPPORT = no
MTK_MPEG_DASH_SUPPORT = no
MTK_MSDC1_NOT_SUPPORT_SDR104 = no
MTK_MT6306_SUPPORT = no
MTK_MT6333_SUPPORT = no
MTK_MT8193_HDCP_SUPPORT = no
MTK_MT8193_HDMI_SUPPORT = no
MTK_MT8193_SUPPORT = no
MTK_MTKLOGGER_SUPPORT = yes
MTK_MTKPS_PLAYBACK_SUPPORT = no
MTK_MULTIBRIDGE_SUPPORT = no
MTK_MULTIPLE_TDLS_SUPPORT = no
MTK_MULTI_PARTITION_MOUNT_ONLY_SUPPORT = no
MTK_MULTI_PS_SUPPORT = yes
MTK_MULTI_SIM_SUPPORT = dsds
MTK_MULTI_STORAGE_SUPPORT = yes
MTK_MULTI_WINDOW_SUPPORT = no
MTK_MUX_CHANNEL = 64
MTK_NAND_MTK_FTL_SUPPORT = no
MTK_NAND_PAGE_SIZE = 2K
MTK_NAND_UBIFS_SUPPORT = no
MTK_NATIVE_FENCE_SUPPORT = no
MTK_NEON_SUPPORT = yes
MTK_NETWORK_LOG_SUPPORT = yes
MTK_NETWORK_TYPE_ALWAYS_ON = no
MTK_NETWORK_TYPE_DISPLAY = no
MTK_NET_RFC7217 = no
MTK_NEW_COMBO_EMMC_SUPPORT = no
MTK_NEW_IPTABLES_SUPPORT = yes
MTK_NFC_ADDON_SUPPORT = no
MTK_NFC_GSMA_SUPPORT = no
MTK_NFC_HCE_SUPPORT = no
MTK_NFC_OMAAC_SUPPORT = no
MTK_NFC_PACKAGE = MTK
MTK_NFC_SE_NUM = 7
MTK_NFC_SUPPORT = no
MTK_NO_NEED_USB_LED = no
MTK_NTFS_OPENSOURCE_SUPPORT = no
MTK_NUM_MODEM_PROTOCOL = 2
MTK_NVCONFIG_PARTITION_SUPPORT = no
MTK_NVRAM_SECURITY = no
MTK_OAT_ON_SDCARD_SUPPORT = no
MTK_OD_SUPPORT = no
MTK_OGG_RECORD_SUPPORT = no
MTK_OGM_PLAYBACK_SUPPORT = no
MTK_OMACP_SUPPORT = yes
MTK_OMADRM_SUPPORT = yes
MTK_OMA_DOWNLOAD_SUPPORT = yes
MTK_ONLY_OWNER_SIM_SUPPORT = no
MTK_OVERLAY_ENGINE_SUPPORT = no
MTK_OWNER_SDCARD_ONLY_SUPPORT = no
MTK_PARTITION_TABLE_PLAIN_TEXT = no
MTK_PASSPOINT_R2_SUPPORT = no
MTK_PCA9575A_SUPPORT = no
MTK_PCM_RECORD_SUPPORT = no
MTK_PERFSERVICE_SUPPORT = no
MTK_PERMISSION_CONTROL = no
MTK_PERSIST_PARTITION_SUPPORT = no
MTK_PHONE_CALL_FIXED_48K_SAMPLERATE = no
MTK_PHONE_VT_VOICE_ANSWER = no
MTK_PLATFORM = MT6739
MTK_PLATFORM_OPTIMIZE = yes
MTK_PLAYBACK_60FPS_TO_30FPS = no
MTK_PMIC_MT6397 = no
MTK_PM_STATS_SUPPORT = no
MTK_POST_PROCESS_FRAMEWORK_SUPPORT = no
MTK_POWER_EXT_DETECT = no
MTK_POWER_PERFORMANCE_STRATEGY_SUPPORT = yes
MTK_PQ_COLOR_MODE = DISP
MTK_PQ_SUPPORT = PQ_HW_VER_2
MTK_PRIVACY_PROTECTION_LOCK = no
MTK_PRODUCER_PARTIAL_UPDATE_SUPPORT = no
MTK_PRODUCT_INFO_SUPPORT = yes
MTK_PROTOCOL1_RAT_CONFIG = C/Lf/Lt/W/T/G
MTK_PROTOCOL2_RAT_CONFIG = L/W/G
MTK_PROTOCOL3_RAT_CONFIG = G
MTK_MULTIPLE_IMS_SUPPORT = 2
MTK_PUMP_EXPRESS_PLUS_20_SUPPORT = no
MTK_PUMP_EXPRESS_PLUS_30_SUPPORT = no
MTK_PUMP_EXPRESS_PLUS_SUPPORT = no
MTK_PUMP_EXPRESS_SUPPORT = no
MTK_QOS_SUPPORT = no
MTK_RADIOOFF_POWER_OFF_MD = no
MTK_RAT_BALANCING = no
MTK_RAT_WCDMA_PREFERRED = no
MTK_RAWFS_NAND_SUPPORT = no
MTK_RCS_SUPPORT = no
MTK_REBOOT_META_SUPPORT = no
MTK_REGIONALPHONE_SUPPORT = no
MTK_RELEASE_PACKAGE = rel_customer_basic rel_customer_kernel_4-4 rel_customer_modem
MTK_RESOLUTION_SWITCH_SUPPORT = no
MTK_RESOURCE_OPTIMIZATION =
MTK_RILD_READ_IMSI = yes
MTK_RIL_MODE = c6m_1rild
MTK_ROTATION_OFFSET_SUPPORT = no
MTK_RSDM_APP = no
MTK_RTP_OVER_RTSP_SUPPORT = yes
MTK_RUNNING_BOOSTER_DEFAULT_ON = yes
MTK_RUNNING_BOOSTER_SUPPORT = no
MTK_RUNNING_BOOSTER_UPGRADE = no
MTK_RUNTIME_PERMISSION_SUPPORT = no
MTK_SCOMO_ENTRY = no
MTK_SCREEN_OFF_WIFI_OFF = no
MTK_SDIOAUTOK_SUPPORT = no
MTK_SEARCH_DB_SUPPORT = yes
MTK_SEC_MODEM_AUTH = no
MTK_SEC_MODEM_ENCODE = no
MTK_SEC_SECRO_AC_SUPPORT = yes
MTK_SEC_VIDEO_PATH_SUPPORT = no
MTK_SEC_WFD_VIDEO_PATH_SUPPORT = no
MTK_SEND_RR_SUPPORT = yes
MTK_SENSORS_1_0 = yes
MTK_SENSOR_BIO = no
MTK_SENSOR_SUPPORT = yes
MTK_SHARED_SDCARD = yes
MTK_SHOW_MSENSOR_TOAST_SUPPORT = no
MTK_SIGNATURE_CUSTOMIZATION = yes
MTK_SIGNMODEM_SUPPORT = no
MTK_SIM1_SOCKET_TYPE = 1
MTK_SIM2_SOCKET_TYPE = 1
MTK_SIM_HOT_SWAP = no
MTK_SIM_HOT_SWAP_COMMON_SLOT = no
MTK_SIM_LOCK_POWER_ON_WRITE_PROTECT = no
MTK_SIM_RECOVERY = yes
MTK_SINGLE_3DSHOT_SUPPORT = no
MTK_SINGLE_IMEI = no
MTK_SLOW_MOTION_VIDEO_SUPPORT = no
MTK_SMARTBOOK_SUPPORT = no
MTK_SMARTSWITCH_SUPPORT = no
MTK_SMSREG_APP = no
MTK_SMS_NATIONAL_LANGUAGE_SUPPORT = no
MTK_SMT_SUPPORT = no
MTK_SOTER_SUPPORT = no
MTK_SPECIFIC_SM_CAUSE = no
MTK_SUBTITLE_SUPPORT = no
MTK_SUPER_DIMMING_SUPPORT = no
MTK_SVP_64BIT_SUPPORT = no
MTK_SWABF_SUPPORT = no
MTK_SWCHR_SUPPORT = yes
MTK_SWIP_WMAPRO = no
MTK_SYSTEM_UPDATE_SUPPORT = no
MTK_TABLET_PLATFORM = no
MTK_TABLET_PLUGIN_BUILD = no
MTK_TABLET_TS_ENHANCEMENT = no
MTK_TB_APP_CALL_FORCE_SPEAKER_ON = no
MTK_TB_APP_LANDSCAPE_SUPPORT = no
MTK_TC1_FEATURE = no
MTK_TC9_FEATURE = no
MTK_TDD_DATA_ONLY_SUPPORT = yes
MTK_TEE_GP_SUPPORT = no
MTK_TEE_SUPPORT = no
MTK_TEE_TRUSTED_UI_SUPPORT = no
MTK_TELEPHONY_BOOTUP_MODE_SLOT1 = 0
MTK_TELEPHONY_BOOTUP_MODE_SLOT2 = 1
MTK_TELEPHONY_CONN_LOG_CTRL_SUPPORT = yes
MTK_TELEPHONY_FEATURE_SWITCH_DYNAMICALLY = no
MTK_TELEPHONY_MODE = 0
MTK_TER_SERVICE = no
MTK_TETHERINGIPV6_SUPPORT = yes
MTK_TETHERING_EEM_SUPPORT = no
MTK_THERMAL_PA_VIA_ATCMD = yes
MTK_THUMBNAIL_OPTIMIZATION = yes
MTK_TINYSYS_SCP_SUPPORT = no
MTK_TINYSYS_SSPM_SUPPORT = no
MTK_TINY_UTIL = no
MTK_TOUCH_BOOST = no
MTK_TTY_SUPPORT = no
MTK_UART_USB_SWITCH = no
MTK_UFS_BOOTING = no
MTK_UFS_OTP = no
MTK_ULTRA_DIMMING_SUPPORT = no
MTK_USB_CBA_SUPPORT = no
MTK_USB_PHONECALL = AP
MTK_USER_ROOT_SWITCH = no
MTK_USER_SPACE_DEBUG_FW = no
MTK_USE_ANDROID_MM_DEFAULT_CODE = no
MTK_USSI_SUPPORT = no
MTK_VIDEO_4KH264_SUPPORT = no
MTK_VIDEO_HEVC_SUPPORT = yes
MTK_VIDEO_VP8ENC_SUPPORT = no
MTK_VILTE_SUPPORT = yes
MTK_VIWIFI_SUPPORT = no
MTK_VOICE_UNLOCK_USE_TAB_LIB = no
MTK_VOIP_ENHANCEMENT_SUPPORT = yes
MTK_VOIP_HANDSFREE_DMNR = no
MTK_VOIP_NORMAL_DMNR = no
MTK_VOLTE_SUPPORT = yes
MTK_VOW_SUPPORT = no
MTK_VPU_SUPPORT = no
MTK_VR_HIGH_PERFORMANCE_SUPPORT = no
MTK_VSS_SUPPORT = no
MTK_VT3G324M_SUPPORT = no
MTK_VZW_CHIPTEST_MODE_SUPPORT = 0
MTK_WAPI_SUPPORT = no
MTK_WAPPUSH_SUPPORT = yes
MTK_WB_SPEECH_SUPPORT = yes
MTK_WEEK_NO = W17.50
MTK_WFC_SUPPORT = no
MTK_WFD_HDCP_RX_SVP_SUPPORT = no
MTK_WFD_HDCP_TX_SUPPORT = no
MTK_WFD_SINK_SUPPORT = no
MTK_WFD_SINK_UIBC_SUPPORT = no
MTK_WFD_SUPPORT = no
MTK_WIFI_MCC_SUPPORT = yes
MTK_WIFI_P2P_SUPPORT = yes
MTK_WIRELESS_CHARGER_SUPPORT = no
MTK_WLANBT_SINGLEANT = no
MTK_WLAN_CHIP = CONSYS_MT6739
MTK_WLAN_PATH_SET = siso
MTK_WLAN_SUPPORT = yes
MTK_WMA_PLAYBACK_SUPPORT = yes
MTK_WMV_PLAYBACK_SUPPORT = yes
MTK_WORLD_PHONE_POLICY = 0
MTK_WPA2PSK_SUPPORT = no
MTK_WVDRM_L1_SUPPORT = no
MTK_WVDRM_SUPPORT = yes
MTK_YAML_SCATTER_FILE_SUPPORT = yes
MTK_YIQI_FONTS_FRAMEWORK_SUPPORT = no
NAND_OTP_SUPPORT = no
NFC_CHIP_SUPPORT = no
NO_INIT_PERMISSION_CHECK = yes
NXP_SMARTPA_SUPPORT = no_nxp
OP01_COMPATIBLE = no
OPTR_SPEC_SEG_DEF = OP09_SPEC0212_SEGC
PURE_AP_USE_EXTERNAL_MODEM = no
SENSOR_BATCH_SUPPORT = no
SIM_ME_LOCK_MODE = 0
SIM_REFRESH_RESET_BY_MODEM = yes
SPM_FW_USE_PARTITION = yes
ST_NFC_FM_SE_CONFIG = 3
TARGET_COPY_OUT_ODM = no
TRUSTONIC_TEE_SUPPORT = no
USE_FRAUNHOFER_AAC = no
USE_XML_AUDIO_POLICY_CONF = 1
WIFI_WEP_KEY_ID_SET = no
BUILD_AGO_GMS = no
MTK_RCS_UA_SUPPORT = no
MTK_NLP_SUPPORT = yes
MTK_AB_OTA_UPDATER = no
MTK_TEMPORARY_DATA_SUPPORT = no
MTK_CAMERA_APP_VERSION = 2
MTK_UT_XCAP_SUPPORT = yes
MTK_OVERRIDES_APKS = yes
MTK_BT_AVRCP_TG_APP_SETTINGS_SUPPORT = yes
MTK_CAM_DLFD_SUPPORT = no
MTK_MMS_IN_GMS = no
CUSTOM_KERNEL_FLAT_SENSOR = no
MTK_IPV6_VZW = no




#--------------------------FactoryTest begin------------------------
BIRD_FTM	= no
BIRD_FACTORY_POWERON_TEST = no
# 产线测试（打开带图标）	
BIRD_FACTORY_POWERON_TEST_PRODUCT_LINE 	= no
#	主摄像头测试	
BIRD_FACTORY_POWERON_TEST_CAM 	= yes
#	副摄像头	
BIRD_FACTORY_POWERON_TEST_SUBCAM 	= no
#	FM	
BIRD_FACTORY_POWERON_TEST_FM 	= yes
#	电池温度	
BIRD_FACTORY_POWERON_TEST_BATTERY_TEM 	= yes
#	WIFI测试
BIRD_FACTORY_POWERON_TEST_WIFI 	= yes
#	传感器、蓝牙、WIFI、GPS测试项：重力传感器	
BIRD_FACTORY_POWERON_TEST_GSENSOR 	= no
#	传感器、蓝牙、WIFI、GPS测试项：蓝牙	
BIRD_FACTORY_POWERON_TEST_BT 	= yes
#	传感器、蓝牙、WIFI、GPS测试项：GPS	
BIRD_FACTORY_POWERON_TEST_GPS 	= yes
#	传感器、蓝牙、WIFI、GPS测试项：近距通信	
BIRD_FACTORY_POWERON_TEST_ALSPS 	= no
#	传感器、蓝牙、WIFI、GPS测试项：指南针	
BIRD_FACTORY_POWERON_TEST_MSENSOR 	= no
#	传感器、蓝牙、WIFI、GPS测试项：陀螺仪	
BIRD_FACTORY_POWERON_TEST_GYROSCOPE 	= no
#	充电指示灯	
BIRD_FACTORY_POWERON_TEST_TIPLAMP 	= no
#	霍尔	
BIRD_FACTORY_POWERON_TEST_HALL 	= no
#	指纹（通信测试）	
BIRD_FACTORY_POWERON_TEST_FINGERPRINT 	= no
#	指纹（带图片效果）	
BIRD_FACTORY_POWERON_TEST_FINGERPRINT_WITH_PICTURE	= no
#	双mic	
MTK_DUAL_MIC_SUPPORT	= no
#	单卡	
BIRD_SINGLE_SIM_ONLY 	= no
#	按键测试 测试项宏控	
BIRD_FACTORY_POWERON_TEST_KEY 	= yes
#	返回键测试	
BIRD_FACTORY_POWERON_TEST_KEY_BACK 	= no
#	拍照键	
BIRD_FACTORY_POWERON_TEST_KEY_CAMERA 	= no
#	FUN1键	
BIRD_FACTORY_POWERON_TEST_KEY_FUN1 	= no
#	HOME 键测试	
BIRD_FACTORY_POWERON_TEST_KEY_HOME 	= no
#	MENU 测试	
BIRD_FACTORY_POWERON_TEST_KEY_MENU 	= no
#	静音键	
BIRD_FACTORY_POWERON_TEST_KEY_MUTE 	= no
#	搜索键	
BIRD_FACTORY_POWERON_TEST_KEY_SEARCH 	= no
#	键盘测试	

BIRD_FACTORY_POWERON_TEST_KEYBOARDLED 	= no
#	耳机测试	
BIRD_FACTORY_AUTO_TEST_HEADSET 	= no
#	按键测试 测试项宏控	
BIRD_FACTORY_AUTO_TEST_MMI_KEY 	= no
#	电池测试防呆	
BIRD_FACTORY_BATTERY_FD 	= no
#	重力传感器测试防呆	
BIRD_FACTORY_GSENSOR_FD 	= no
#	NFC	
BIRD_FACTORY_POWERON_TEST_NFC 	= no
#	OTG	
BIRD_FACTORY_POWERON_TEST_OTG 	= no

#* 988e146 - (7131SQ7_F555_171021) 移植双摄factory test : BIRD_FACTORY_TEST_BACKUPCAMERA=[0,1] 0是后摄双摄,1是前摄双摄 (12 hours ago) <zhangbiby>

#BIRD_FACTORY_TEST_BACKUPCAMERA =0

#--------------------------FactoryTest end------------------------
#--------------------------MMI Test begin------------------------
BIRD_MMI_AUTO_TEST=yes
##check following exist devices and set yes,Or set no.
#device GPS
BIRD_MMI_AUTO_TEST_GPS = yes
BIRD_MMI_AUTO_TEST_GPS_MANUAL_CHECK = yes
#device light sensor
BIRD_MMI_AUTO_TEST_LIGHT_SENSOR = no
#device Gravity Sensor
BIRD_MMI_AUTO_TEST_SENSOR = no
BIRD_MMI_AUTO_TEST_SENSOR_Z = no
#device LED
BIRD_MMI_AUTO_TEST_LED = no
#device Wifi
BIRD_MMI_AUTO_TEST_WIFI = yes
#device flashlight
BIRD_MMI_AUTO_TEST_FLASHLIGHT = no
#device sub camera
BIRD_MMI_AUTO_TEST_SUB_CAMERA = no
#device BlueTooth
BIRD_MMI_AUTO_TEST_BT = yes
#device main camera
BIRD_MMI_AUTO_TEST_MAIN_CAMERA = yes
#device acceleration sensor
BIRD_MMI_AUTO_TEST_ACCELERATION = no
#device FM
BIRD_MMI_AUTO_TEST_FM = yes
#device Proximity sensor
BIRD_MMI_AUTO_TEST_PROXIMITY = no
#device TouchPanel
BIRD_MMI_AUTO_TEST_TOUCH = yes
#headset test
BIRD_MMI_AUTO_TEST_HEADSET = yes
#OTG
BIRD_MMI_AUTO_TEST_OTG = no
#HALL
BIRD_MMI_AUTO_TEST_HALL = no
#NFC
BIRD_MMI_AUTO_TEST_NFC = no
#MSENSOR
BIRD_MMI_AUTO_TEST_COMPASS = no
BIRD_MMI_AUTO_TEST_GYROSCOPE = no
BIRD_MMI_AUTO_TEST_KEYBOARDLED = no
BIRD_MMI_AUTO_TEST_LCD_TAP = yes
#TIPLAMP
BIRD_MMI_AUTO_TEST_TIPLAMP = no
#FINGERPRINT
BIRD_MMI_AUTO_TEST_FINGERPRINT = no
BIRD_MMI_AUTO_TEST_FINGERPRINT_WITH_PICTURE=no
BIRD_MMITEST_TPDRAW_FWVGA = yes
BIRD_MMI_AUTO_TEST_DIAL112 = no
BIRD_MMI_AUTO_TEST_BATTERY_ID = yes
#STORAGE INFO
BIRD_MMI_STORAGE_INFO=yes
BIRD_MMI_RESTORE_FACTORY=yes
#BIRD_MMI_BACKUPCAMERA=0
#BIRD_MMI_BACKUPCAMERA_FD=yes
#
BIRD_MMI_INFRARED_LED_TEST = yes

#--------------------------MMITest end------------------------
#--------------------------|DRV Config Begin |------------------------
BIRD_CUSTOM = 8121TO_Q2801_MV88Y_V05_QVGA
#-----|IMGSENSOR Begin  |------
BIRD_MAIN_IMGSENSOR = gc5025_mipi_raw_8121TO_Q2801_MV88Y_V05_QVGA_SQ
# BIRD_MAIN_BACKUP_IMGSENSOR = 
BIRD_SUB_IMGSENSOR = gc2385_mipi_raw_8121TO_Q2801_MV88Y_V05_QVGA_SQ
# BIRD_SUB_BACKUP_IMGSENSOR = 
#-----|IMGSENSOR End    |------
#----------|bird config Begin|-----------
BIRD_MCP_CUSTOM_MEMORYDEVICE = MEV88__MT6739_EVB
BIRD_SW_PLATFORM = BIRD_O1MP1_K39TV1_BSP
#----------|bird config End	 |-----------
#----------|LCD Begin        |-----------
BIRD_LCD_DENSITY = 120
#----------|LCD End          |-----------
#----------|TP Begin         |-----------
#虚拟按键  
#BIRD_HAS_NAVBAR = yes
#----------|TP End           |-----------
#----------|camera Begin     |-----------
#-----|IMGSENSOR Begin  |------
# BIRD_MAIN_IMGSENSOR = 
# BIRD_MAIN_LENS = 
# BIRD_MAIN_BACKUP_IMGSENSOR =
# BIRD_SUB_IMGSENSOR = 
# BIRD_SUB_BACKUP_IMGSENSOR = 
#-----|IMGSENSOR End    |------
#----------|camera End       |-----------
#----------|fingerprint Begin|-----------
#----------|fingerprint End  |-----------
#----------|alsp Begin       |-----------
#----------|alsp End         |-----------
#----------|wifi Begin       |-----------
#----------|wifi End         |-----------
#----------|FM   Begin       |-----------
#----------|FM   End         |-----------
#----------|GPS Begin        |-----------
#----------|GPS End          |-----------
#----------|GSENSOR Begin    |-----------
#----------|GSENSOR End      |-----------
#--------------------------|DRV Config End   |------------------------
#--------------------------|GUI Config Begin |------------------------
#----------|NAME 	Begin      |-----------

#ro.product.brand
# 你想改的品牌
BIRD_PRODUCT_BRAND = DOOV

#ro.product.name
# 你想要的手机名
BIRD_PRODUCT_NAME = 2019

# ro.bdmisc.device_name

BIRD_DEVICE_NAME = X1
# ro.build.tags
#BIRD_BUILD_VERSION_TAGS = release-keys

# 蓝牙名称
BIRD_BT_STRING=2019
#ro.product.device
BIRD_PRODUCT_DEVICE =2019
# ro.product.model 关于中的手机型号
BIRD_PRODUCT_MODEL =2019
# Wlan 直连名称
BIRD_WLAN_DIRECT_NAME = 2019
# wlan 热点名称
BIRD_WLAN_SSID_STRING = 2019


# ro.product.manufacturer改上你喜欢的手机制造商
BIRD_MTP_MANUFACTURER = DOOV
# 照片的名称
BIRD_EXIF_STRING_MAKE = 2019
BIRD_EXIF_STRING_MODEL = 2019


# ro.bdmisc.mtp_model MTP连接时电脑上的显示名称
BIRD_MTP_MODEL = 2019
# ro.bdmisc.mtp_label
BIRD_MTP_LABEL = 2019
BIRD_PRODUCT_STRING = 2019
BIRD_PRODUCT_BOARD = 2019
#----------|NAME 	End	       |-----------
#----------|Powen ON 	Begin	 |-----------
# 开机log配置 路径
# AD_prototype_FHD_LOGO  AD_prototype_FWVGA_LOGO  AD_prototype_HD_LOGO  AD_prototype_QHD_LOGO  AD_prototype_QVGA_LOGO  AD_prototype_WVGA_LOGO
# bird/logo/first-second_logo/
BIRD_FIRST_LOGO = DOOV_QVGA_LOGO
BIRD_SECOND_LOGO = DOOV_QVGA_LOGO

# 开关机动画 
# AD_prototype_FHD_BOOT_ANI  AD_prototype_FWVGA_BOOT_ANI  AD_prototype_HD_BOOT_ANI  AD_prototype_QHD_BOOT_ANI  AD_prototype_QVGA_BOOT_ANI  AD_prototype_WVGA_BOOT_ANI
# bird/logo/boot_animation/  bird/logo/shut_animation/
BIRD_BOOT_ANIMATION = DOOV_QVGA_BOOT_ANI
BIRD_SHUTDOWN_ANIMATION = DOOV_QVGA_SHUT_ANI

# 开机铃声
# bird/sounds/boot/  bird/sounds/shutdown/
#BIRD_BOOT_RING = boot_ring
BIRD_SHUTDOWN_RING = 
#----------|Powen ON 	End		 |-----------
#----------|Ring 	Begin			 |-----------
#----------|Ring 	End				 |-----------
#----------|WALLPAPER 	Begin|-----------
#----------|WALLPAPER 	End  |-----------
#----------|Launcher Begin   |-----------
#----------|Launcher End     |-----------
#----------|THEME Begin			 |-----------
#----------|THEME End 			 |-----------
#----------|Status bar Begin |-----------
#----------|Status bar End   |-----------
#----------|MUSIC Begin			 |-----------
#----------|MUSIC End 			 |-----------
#----------|Other GUI Begin	 |-----------
#----------|Other GUI End    |-----------
#--------------------------|GUI Config End   |------------------------
#--------------------------|OTA Begin				 |------------------------

# 打开广升ota 避免编译停顿
ADUPS_FOTA_SUPPORT = no

# 关闭自动编译ota包，避免编译停顿
BIRD_AUTO_MAKE_OTA=no
#--------------------------|OTA End		      |------------------------
#--------------------------|SETTING Begin		|------------------------
#----------|USB MCP Begin			 |-----------
BIRD_DEFAULT_CONNECTION_MTP=yes
#----------|USB End					 |-----------
#----------|Lang Input  Begin|-----------
#----------|Lang Input  End  |-----------
#----------|Call  Begin      |-----------
#----------|Call End         |-----------
#----------|MMS Begin				 |-----------
#----------|MMS End					 |-----------
#----------|Data   Begin		 |-----------
#----------|Data    End			 |-----------
#----------|Date Time Begin	 |-----------
#----------|Date Time End		 |-----------
#----------|Email Begin      |-----------
#----------|Email End        |-----------
#----------|Browser Begin    |-----------
#----------|Browser End      |-----------
#----------|Other SETTING Begin
BIRD_AM_PM_AFTER_TIME=yes
BIRD_LEFT_KEY_UNLOCK=yes
BIRD_CAN_CLOSE_KEY_LIGHT=yes
BIRD_MENU_MOBILE_GUIDE=yes
BIRD_STATUS_BAR_A16=yes
#CTA, factory mouse
#BIRD_UINPUT_MOUSE = yes
BIRD_KEYBOARD_PROJECT_CUSTOM = Q2801
#BIRD_LONG_PRESS_POWER_SHUT_OFF = yes
BIRD_FAMILY_CALL_NUMBER=9
BIRD_HOME_LONGPRESS_KEYEVENT_TYPE = bihee
BIRD_MASTER_CLEAR_PASSWORD = 0000
BIRD_APK_keyboard_SOS = yes
BIRD_APK_keyboard_LocService = yes
BIRD_TURN_OFF_SCREEN_BY_TIMER = yes
BIRD_MINIMUM_SCREEN_OFF_TIMEOUT = 5000
BIRD_SCREEN_DIM_DURATION = 3000
TEST_HAS_OVERLAY_CONFIG=yes
BIRD_SUPPORT_FLASHLIGHT = no
BIRD_GEO_DESCRIPTION=yes
BIRD_REMOVE_VIDEO_CALL_MENU=yes
BIRD_UNREAD_VIEW_CHANGE_STYLE = yes
#----------|Other SETTING End  |-----------
#--------------------------|SETTING End			|------------------------
#--------------------------|APK Add Begin		|------------------------
#----------|GMS  Begin  |-----------
#----------|GMS  End    |-----------
#--------------------------|APK Add End  		|------------------------
#--------------------------|Must Open Begin |------------------------
BIRD_CTCC_REGISTER_MODEL = 2019
BIRD_CTCC_REGISTER_SWVER = 2019_V1.00
BIRD_CTCC_HARDWARE_VERSION = 8121T0_MMI_V01
BIRD_IP_ADDRESS_FIXED = yes
#----------|Command  Begin   |-----------

# 查询硬件指令
# "*#732873#*"
BIRD_HARDWARE_INFO = yes

# 配置通过指令 *#0*跳过开机向导
##BIRD_SKIP_SETUPWIZARD = yes

# *#15位号码#6666#指令写码功能 默认开启，no 为关闭
BIRD_WRITE_IMEI = yes 



# 配置编码（如：287596263）
BIRD_CONFIG_CODE=287941658
# 兼容标识（如：A1）
BIRD_COMPATIBLE_MARK=A1
# 启用拨号指令 显示兼容配置检查结果 *#17373#* 
BIRD_COMPATIBLE_MARK_CHECK_APK = yes

BIRD_NOTFORBID_INSTALLING_APP = yes

BIRD_PARA_INFO_CONFIG = 8121TO_Q2801_MV88Y_V05_QVGA

BIRD_REMOTE=yes

BIRD_MMI_HAS_SOS=yes
BIRD_REMOVE_CENTER_SOS=yes

BIRD_GEMINI_RINGTONE=yes

BIRD_WIFI_SIGNAL_FAKE=yes

BIRD_DEVELOPMENT_DEF_ON=no

BIRD_DATA_DEFAULT_OFF=true



BIRD_BOOT_SWITCH=yes


#----------|Command  End		 |-----------
#--------------------------|Must Open End		|------------------------
#--------------------------|Other  Begin              |------------------------
#keyboard
BIRD_PKG_SOUND_RECORDER=yes
BIRD_DEFAULT_LANGUAGES_PRODUCT_LOCALES=zh_CN
BIRD_DEFAULT_WALLPAPER=Q2801_wallpape_240_320
#BIRD_EXTRA_WALLPAPERS=A16_QVGA_BIHEE
#--------------------------|Other  End		|------------------------
#--------------------------|SW_VERSION Begin|------------------------
BIRD_INNER_SW_VERSION = 8121TO.Q2801.A1.190528.AD81.V01.QVGA.MEV88.P1.MP.CN

BIRD_BUILD_VERNO = Q2801-8121T0-DV-AZ-20190528-V0102
BIRD_EM_VERNOE = Q2801-8121T0-DV-AZ-20190528-V0102
BIRD_CUSTOM_SW_VERSION = Q2801-8121T0-DV-AZ-20190528-V0102

BIRD_INNER_QK_VERSION = Q2801-8121T0-DV-AZ-20190528-V0102
BIRD_CMCC_SOFTWARE_VERSION = 2019_V1.00
BIRD_CMCC_HARDWARE_VERSION = 8121TO_MMI_V01


#--------------------------|SW_VERSION End  |------------------------
#--------------------------|*****************|------------------------
#----------|*****************|-----------
#-----|*****************|------
#-----|*****************|------
#----------|*****************|-----------

#--------------------------|FEEME ADD START |------------------------
FREEME_PRODUCT_Q2801_REQUIRE = yes
#--------------------------|FEEME ADD END |------------------------
